//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBook.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#if !defined(_TBOOK_H)
#define _TBOOK_H
#include <string>
using namespace std;

class TBook {
private:
	string bookTitle;
	string shelfMark;
public:
	TBook()
	{
		cout << "Konstruktor klasy TBook" << endl;
	}
	~TBook()
	{
		cout << "Konstruktor klasy TBook" << endl;
	}
	void setTitle(string title);
	string getTitle();
	void getShelfMark(string mark);
	string getShelfMark();

};

#endif  //_TBOOK_H
