//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//

#include <iostream>
#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"
using namespace std;
class Jamnik : public Pies {
public:
	
	double w;
	int Operation4(int x);
	
	Jamnik() {
	w = w++;
	cout << "Utworzono Jamnika nr " << w << endl;
}
};

#endif  //_JAMNIK_H
