//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H

#include "Zwierze.h"

class Ssak : public Zwierze {
public:
	int y;
	int Operation2(int x);
}; 

#endif  //_SSAK_H
