//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Ssak.h"

int Ssak::Operation2(int x) {
return x; 
}

