//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#if !defined(_TUNIVERSITY_H)
#define _TUNIVERSITY_H

#include "TStudent.h"

class TUniversity {

private:
	TStudent student;
	string name;
	
public:
	TUniversity(string univName)
	{
		name = univName;
		cout << name << endl;
	}
	void printData()
	{
		cout << student.getName() << endl;
		cout << student.getAge() << endl;
	}
	void setData(string name, int age)
	{
		student.setName(name);
		student.setAge(age);
	}

};

#endif  //_TUNIVERSITY_H
