//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author : 
//
//


#include "TUniversity.h"

void TUniversity::attach() {

}

void TUniversity::detach() {

}

