//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.h
//  @ Date : 12.03.2018
//  @ Author : 
//
//


#if !defined(_TUNIVERSITY_H)
#define _TUNIVERSITY_H


class TUniversity {
private:
	vector <TStudent*> students;
	vector <TStudent*>::iterator it;
public:
	void attach()
	{
		TStudent* stid = new TStudent[5];
		students.push_back(stud);
	}
	void detach()
	{
		for (it=students.begin(); it!=students.end(); ++it)
 		delete [] *it;
	}

};

#endif  //_TUNIVERSITY_H
