//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Jamnik.h"

int Jamnik::test3(int x) {

}

