//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Ssak.h"

double Ssak::test1(double z) {

}

