//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBook.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//

#include <iostream>
#if !defined(_TBOOK_H)
#define _TBOOK_H
#include <string>
using namespace std;

class TBook {
private:
	string bookTitle;
	string shelfMark;
public:
	TBook()
	{
		cout << "Konstruktor klasy TBook" << endl;
	}
	~TBook()
	{
		cout << "Konstruktor klasy TBook" << endl;
	}
	void setTitle(string title)
	{
		bookTitle = title;
	}
	string getTitle()
	{
		return bookTitle;
	}
	void getShelfMark(string mark)
	{
		shelfMark = mark;
	}
	string getShelfMark()
	{
		return shelfMark;
	}

};

#endif  //_TBOOK_H
