//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLibrary.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#if !defined(_TLIBRARY_H)
#define _TLIBRARY_H
#include <iostream>
#include <string>
using namespace std;

class TLibrary {
private:
	TBook* book;
	string libraryName;
public:
	TLibrary(string libName)
	{
		libraryName = libName;
		cout << libName <<endl;
		book = new TBook;
	}
	~TLibrary() 
	{
		delete book;
	}
	void printData()
	{
		cout << book->getTitle() << "\t";
 		cout << book->getShelfMark() <<endl;
	}
	void setData(string title, string mark)
	{
		book->setTitle(title);
 		book->setShelfMark(mark);

	}

};

#endif  //_TLIBRARY_H
