//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.cpp
//  @ Date : 12.03.2018
//  @ Author : 
//
//


#include "TStudent.h"

TStudent::TStudent() {

}

TStudent::~TStudent() {

}

void TStudent::setName(string name) {

}

string TStudent::getName() {

}

void TStudent::setAge(int age) {

}

int TStudent::getAge() {

}

