//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.h
//  @ Date : 12.03.2018
//  @ Author : 
//
//


#if !defined(_TSTUDENT_H)
#define _TSTUDENT_H
#include <vector>
#include <iostream>
using namespace std;

class TStudent {
private:
	string studentName;
	int studentAge;
	
public:
	TStudent()
	{
		cout << "Konstruktor TStudent" << endl;
	}
	~TStudent()
	{
		cout << "Destruktor TStudent" << endl;
	}
	void setName(string name)
	{
		studentName = name;
	}
	string getName()
	{
		return studentName;
	}
	void setAge(int age)
	{
		studentAge = age;
	}
	int getAge()
	{
		return studentAge;
	}

};

#endif  //_TSTUDENT_H
