//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author : 
//
//


#include "TUniversity.h"

void TUniversity::attach(TStudent* st) {

}

void TUniversity::detach() {

}

void TUniversity::printData(int i) {

}

void TUniversity::setData(int i, string name, int age) {

}

