//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.h
//  @ Date : 12.03.2018
//  @ Author : 
//
//


#if !defined(_TUNIVERSITY_H)
#define _TUNIVERSITY_H
#include <vector>
#include <iostream>
using namespace std;

class TUniversity {
private:
	vector<TStudent*> students;
public:
	void attach(TStudent* st)
	{
		students.push_back(st);
	}
	void detach()
	{
		students.pop_back();
		cout << "Po usunieciu elementow, vector TStudent " << (students.empty()?"jest":"nie jest") << " pusty" << endl;
	}
	void printData(int i)
	{
		cout << students[i] -> getName() << endl;
		cout << students[i] -> getAge() << endl;
	}
	void setData(int i, string name, int age)
	{
		students[i] -> setName(name);
		students[i] -> setAge(age);
	}

};

#endif  //_TUNIVERSITY_H
