//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.cpp
//  @ Date : 12.03.2018
//  @ Author : 
//
//


#include "TStudent.h"

TStudent::TStudent() {

}

TStudent::~TStudent() {

}

