//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//

#include <iostream>
#include <string>
#if !defined(_TSTUDENT_H)
#define _TSTUDENT_H
using namespace std;

class TStudent {
private:
	string studentName;
	int studentAge;
	
public:
	void setName(const string& name) 
	{
	studentName = name;
	}
	
 	string getName() const 
	{
	 return studentName;
	}
	
 	void setAge(const int age) 
	{
	studentAge = age;
	}
	
 	int getAge() const 
	{
	return studentAge;
	}

};

#endif  //_TSTUDENT_H
