//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.cpp
//  @ Date : 05.03.2018
//  @ Author : 
//
//

#include <iostream>
#include <string>
#include "TStudent.h"
using namespace std;

void TStudent::setName(string name) {

}

string TStudent::getName() {

}

void TStudent::setAge(int age) {

}

int TStudent::getAge() {

}

